apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "restic-backup.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "restic-backup.labels" . | nindent 4 }}
rules:
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    resourceNames:
      - {{ .Values.backup.statefulSetName | quote }}
    verbs: ["get", "patch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    resourceNames:
      - {{ .Values.backup.dataPvcName | quote }}
    verbs: ["get"]
