---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-user: AgChBvY8I3gfbtbVUnXedpVRNa55ma7KtcXCj92ZMu7JwRxxvn01g3UYhRQRx9nVSgeEmK3o5GiBdK96Yyvj+u170VqxqakV5tdEvl2u5xJxkGNEk7fqrNMcSfwTxyGMXrfeJMtjkHcXAuFg3rRuo+YLOYf9vRQC5Yd99qixF4P+4R43J2Vp0S0BvqJ8JrYVQvNCIJNmXcIu8NuLar+LH17XXdqX6XbiLXD4iq4SGd/9YzgLgx4eZh/uBPUWMhoDKRIV+5lZNaV/DErNHDcpQOLZztTlYUbMwgrwKhrpYpynh1x6WjgPpdP88zV4kuXN3vydocueYxiKLhTCW1BTzECm6el1H4yar10Une2YC77CmbLvXJepZrlwUekUgAX/02nEHmvKc6EBBD+8lHQxaLcW0n8/2axpoAm5/EIr0sR+2lc+3I86jY8r69fJMs3EIGPSAhiIGIToiH2BBYNyVDdN0+XTSKsTaz9zJRnsaTFsEBeTfEnG7RulGZGw4tx6pDmYEODJM/rEs4pQ4TQDKVc02jOw4jqbbP/yvrNEZWZQLf9jMkX1eaPMebYhswkccwN0EhKuLWN8B595fxwcyRl/7WgKfa34mTwgL+Sp8T9BDEVxcaRutlZCGh+yodMDZEyJ1CF660nSUkFZHVZ/O7yTuH7qML2n5kk5xklHgFAEbux/NGHuOLSvsQPAQZ3Uks5XuvoKRg==
    admin-password: AgB4plUp+HBFAlsLR4mXEgpSIuphraZs7TRu1c8ihLR0Pd2jprvOtWugFV06CMcjgdaLMM1qUwTZ9Wy645NC2TyzHDlA6PZUKcNG/hNSH6bHJdWWkKeZAMooaOXUvAMbulwcaX1AxDaVZndUKTkvkprxjDj80Tfj3eeec8FQkOnW8mvrH74HqPLuMDMaxylpTXIYGOnkLHX3APguaqDoDRQYlZ8kUlybfjnFImjKbcKrNwas35vvNfHr42IoK/SMJH/fVEp/RD1g+kqzyiktm3oodJKCYjorVOIMTmDCDet7MiKsWg9AYtC5ePegYENLhRtrRKPUIoy00p3p8YuBTUF8CLwWtBIhnM3TTaEXMI6COoiya2ehlCBmDamZyn531+0vGyzly+PgWgdDGEpSiAbYTtTB8WvVCTReoENBO+/5uXKlnH2WXc9BXyQuP+S1Ti+t29JGLAnPNd2YlBpqE8HIt4TkE459MxAMMKDKDfkMYOX7euJE9ylDE4QH8YdbQsXG5m/pk3O8oKl9y8TPRGH+pFyo5uHa4OAkWFcOTgoN+UQg8lMpZhFzwtajE0vBRcXg2B1diqe5+H2omWeeeEi3uSYMJIYtZnK58O+K5kRTUlpeo+VlUNKzbru98zsk1sijKsHdw99nTYzL+CPxIXAqylM9AKMZWd5QBE9zOkStqYvWCFvP50aEFHwMEGB8GdhNMpdvlxXkCGODuKyc
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-credentials
      namespace: monitoring
