---
# ==============================================================================
# LOCAL INVENTORY - DO NOT COMMIT THIS FILE
# ==============================================================================

all:
  hosts:
    homelab:
      ansible_host: "192.168.50.100"
      ansible_user: "alex"
      ansible_become_password: "1234"
      ansible_ssh_private_key_file: "~/.ssh/id_ed25519"
      ssh_public_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILIZyrectqSGfJAaYNqJR0s25JYU8tc8iQb4GRsJHQyL alex@ALEX-PC"  # REPLACE THIS WITH YOUR REAL PUBLIC KEY
      ansible_python_interpreter: /usr/bin/python3
  vars:
    # Environment-specific overrides
    nfs_server: "192.168.50.110"
    nfs_base_export: /volume1/data
  children:
    k3s_servers:
      hosts:
        homelab:
