apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "adguardhome.fullname" . }}-config
  labels:
    {{- include "adguardhome.labels" . | nindent 4 }}
data:
  AdGuardHome.yaml: |
    bind_host: 0.0.0.0
    bind_port: 3000

    dns:
      bind_hosts:
        - 0.0.0.0
      port: 53

      # Filter + protection
      protection_enabled: true
      filtering_enabled: true
      blocking_mode: default
      blocked_response_ttl: 10

      upstream_dns:
        - 8.8.8.8
        - 8.8.4.4

      # Map all local *.home names to the k3s node IP.
      rewrites:
        - domain: '*.home'
          answer: 192.168.50.100

      # Periodically refresh filter lists.
      filters_update_interval: 24

    filters:
      - enabled: true
        url: https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
        name: AdGuard DNS filter
        id: 1

    http:
      address: 0.0.0.0:3000
      session_ttl: 720h
      enable_json_api: true
