{{- if .Values.sealedSecret.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "vaultwarden.fullname" . }}-admin
  labels:
    {{- include "vaultwarden.labels" . | nindent 4 }}
spec:
  encryptedData:
    admin-token: "REPLACE_WITH_SEALED_VALUE"
  template:
    metadata:
      name: {{ include "vaultwarden.fullname" . }}-admin
      labels:
        {{- include "vaultwarden.labels" . | nindent 8 }}
{{- end }}
