apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cluster-backup.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "cluster-backup.labels" . | nindent 4 }}
